### ISSUE TITLE
hope multisign contract have this...

### ISSUE THREAD

**Issue by purplecity** [TezTech/tzcontracts#2]
1  can deploy to get a KT1 address

2 has owners. transaction operation need some of owners agree

3 can send to tz1 or KT1 address

4 can deposit to self contract (not need owners agree)

5 other logic--- internel operation should check self contract balance is enough.  not allow xtz while managing multisig...

...  am I asking too much and being rude?  .........

**Comment by stephenandrews** [comment]
This smart contract does all of this: https://github.com/TezTech/tzcontracts/blob/master/multi_sig/basic.fi

**Comment by purplecity** [comment]
but it can't deploy to get a KT1 address....  are u in New Zealand? if u in New Zealand. we can chat because no too much time difference。 I am in beijing

**Comment by stephenandrews** [comment]
What do you mean? You can compile it to michelson and originate it like a standard smart contract

**Comment by purplecity** [comment]
I compile to it,but don't know how to originate it ....


parameter bytes;storage (pair (map bytes (set address)) (pair nat (set address)));code{DUP;CDR;NIL operation;PAIR;SWAP;CAR;DUP;PUSH bytes 0x;COMPARE;EQ;IF{DROP}{DUP;PUSH nat 4;PUSH nat 0;SLICE;IF_NONE{PUSH nat 100;FAILWITH}{};DUP;PUSH bytes 0x544f0a12;COMPARE;EQ;IF{DROP;DUP;SIZE;PUSH nat 4;SWAP;SUB;DUP;GT;IF{}{PUSH nat 102;FAILWITH};ABS;PUSH nat 4;SLICE;IF_NONE{PUSH nat 101;FAILWITH}{};UNPACK (pair address mutez);IF_NONE{PUSH nat 103;FAILWITH}{};PAIR;NONE (set address);NONE bytes;PAIR;PAIR;SENDER;DIP{SOURCE};COMPARE;EQ;IF{}{PUSH string "Failed assert";FAILWITH};SENDER;DIP{DUP;CDDDDDR};MEM;DIP{PUSH bool True};COMPARE;EQ;IF{}{PUSH string "Failed assert";FAILWITH};DUP;CDAR;PACK;SWAP;SET_CAAR;EMPTY_SET address;SWAP;SET_CADR;DUP;CAAR;DIP{DUP;CDDDAR};MEM;DIP{PUSH bool True};COMPARE;EQ;IF{DUP;CAAR;DIP{DUP;CDDDAR};GET;IF_NONE{PUSH string "Key not found in map";FAILWITH}{};SWAP;SET_CADR}{};SENDER;DIP{DUP;CADR};MEM;DIP{PUSH bool True};COMPARE;NEQ;IF{}{PUSH string "Failed assert";FAILWITH};SENDER;DIP{PUSH bool True};DIIP{DUP;CADR};UPDATE;SWAP;SET_CADR;DUP;CADR;SIZE;DIP{DUP;CDDDDAR};COMPARE;EQ;IF{DUP;CAAR;DIP{NONE (set address)};DIIP{DUP;CDDDAR};UPDATE;SWAP;SET_CDDDAR;UNIT;DIP{DUP;CDADR};DIIP{DUP;CDAAR;CONTRACT unit;IF_NONE{PUSH string "Invalid contract";FAILWITH}{}};TRANSFER_TOKENS;DIP{DUP;CDDAR};CONS;SWAP;SET_CDDAR}{DUP;CAAR;DIP{DUP;CADR;SOME};DIIP{DUP;CDDDAR};UPDATE;SWAP;SET_CDDDAR};CDDR}{DROP;PUSH nat 400;FAILWITH}}}

**Comment by purplecity** [comment]
I compiled it but I don't know how to originate it.  Example:at try_liquidity. I can use some manager to deploy, https://fi-code.com I don't know to originate it.  at Python script I don't know "map bytes(set address) request" meaning...

parameter bytes;storage (pair (map bytes (set address)) (pair nat (set address)));code{DUP;CDR;NIL operation;PAIR;SWAP;CAR;DUP;PUSH bytes 0x;COMPARE;EQ;IF{DROP}{DUP;PUSH nat 4;PUSH nat 0;SLICE;IF_NONE{PUSH nat 100;FAILWITH}{};DUP;PUSH bytes 0x544f0a12;COMPARE;EQ;IF{DROP;DUP;SIZE;PUSH nat 4;SWAP;SUB;DUP;GT;IF{}{PUSH nat 102;FAILWITH};ABS;PUSH nat 4;SLICE;IF_NONE{PUSH nat 101;FAILWITH}{};UNPACK (pair address mutez);IF_NONE{PUSH nat 103;FAILWITH}{};PAIR;NONE (set address);NONE bytes;PAIR;PAIR;SENDER;DIP{SOURCE};COMPARE;EQ;IF{}{PUSH string "Failed assert";FAILWITH};SENDER;DIP{DUP;CDDDDDR};MEM;DIP{PUSH bool True};COMPARE;EQ;IF{}{PUSH string "Failed assert";FAILWITH};DUP;CDAR;PACK;SWAP;SET_CAAR;EMPTY_SET address;SWAP;SET_CADR;DUP;CAAR;DIP{DUP;CDDDAR};MEM;DIP{PUSH bool True};COMPARE;EQ;IF{DUP;CAAR;DIP{DUP;CDDDAR};GET;IF_NONE{PUSH string "Key not found in map";FAILWITH}{};SWAP;SET_CADR}{};SENDER;DIP{DUP;CADR};MEM;DIP{PUSH bool True};COMPARE;NEQ;IF{}{PUSH string "Failed assert";FAILWITH};SENDER;DIP{PUSH bool True};DIIP{DUP;CADR};UPDATE;SWAP;SET_CADR;DUP;CADR;SIZE;DIP{DUP;CDDDDAR};COMPARE;EQ;IF{DUP;CAAR;DIP{NONE (set address)};DIIP{DUP;CDDDAR};UPDATE;SWAP;SET_CDDDAR;UNIT;DIP{DUP;CDADR};DIIP{DUP;CDAAR;CONTRACT unit;IF_NONE{PUSH string "Invalid contract";FAILWITH}{}};TRANSFER_TOKENS;DIP{DUP;CDDAR};CONS;SWAP;SET_CDDAR}{DUP;CAAR;DIP{DUP;CADR;SOME};DIIP{DUP;CDDDAR};UPDATE;SWAP;SET_CDDDAR};CDDR}{DROP;PUSH nat 400;FAILWITH}}}

**Comment by stephenandrews** [comment]
You can read more about deploying Michelson contracts here: http://tezos.gitlab.io/mainnet/whitedoc/michelson.html - also here's an article that details originating a michelson contract: https://medium.com/@brice.aldrich/getting-started-with-fi-a8eea75733db

We will be putting together a blog post in future with more details too.

**Comment by purplecity** [comment]
still not understand bytes now. could tell me a example... it is the private key of address who deploy this contract?

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/38914615/53775796-cbb20d80-3f2e-11e9-82af-b48d55b3a4b8.png">

**Comment by stephenandrews** [comment]
You need to read up on Michelson so you can enter the literal values in. For the requests, you want to enter an empty big map which is {}

For storage.owners, that's a set so you need to enter it in as a Michelson set, which is {"tz1"; "tz2"; "tz3";} etc

Please read the Michelson documentation - to understand the basics of Michelson when trying to deploy a Michelson smart contract

**Comment by stephenandrews** [comment]
As mentioned, an article will be posted in the future as well

**Comment by purplecity** [comment]
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/38914615/53775993-8215f280-3f2f-11e9-86ff-d2bf6bdedc28.png">

**Comment by purplecity** [comment]
actually at Tezos. it's the last job that transfer between 2 KT1 address(also include KT1->tz1). so sometimes I don't want spend more time on tezos. our exchange now  need more cryptocurrency to list.

**Comment by stephenandrews** [comment]
Owners is wrong, it needs to be {"tz1"; "tz2"; "tz3"} like I said in my previous post. Here's the exact page which references it: http://tezos.gitlab.io/mainnet/whitedoc/michelson.html#iii-core-data-types-and-notations

**Comment by purplecity** [comment]
still wrong . I input the owners is :

{"tz1eSeLtoZwbi6hCbepRcsoQiLzTaeAMK59J";"tz1cVmYsgYSux2Ng7cgH9FpybMNdUKAdtChy";"tz1UwLrUSCznFfdsiRmmw1dYZLXMnVsnq38z"}

question is :  is not need a account to deploy this contract?


<img width="1332" alt="image" src="https://user-images.githubusercontent.com/38914615/53776725-da4df400-3f31-11e9-8121-35d48096cc94.png">

**Comment by stephenandrews** [comment]
You haven't selected a contract entry

**Comment by stephenandrews** [comment]
I recommend you read through the fi documentation, the Michelson documentation, and the example in the article by Brice that I linked earlier. If you follow those, you will be able to get this running.

**Comment by purplecity** [comment]
ok. I go to read documentation. really thanks. but I always have a problem is :  deploy this contract not need a account or fee?

**Comment by stephenandrews** [comment]
To originate, it does cost - transaction fee and an origination burn. I'll try and get an article together asap for this though.

**Comment by purplecity** [comment]
hello Stephen. I read  https://medium.com/@brice.aldrich/getting-started-with-fi-a8eea75733db and some of http://tezos.gitlab.io/mainnet/whitedoc/michelson.html . then I step by step:

1 I  compile u basic.fi to this. and copy the ml:contents to create a test.fl.ml file. not include ' '
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/38914615/53852264-64628f00-3ffc-11e9-9070-c8a646761f67.png">

2 at my docker node  use follow to originate it. but failed. is my init form at not correct?
./alphanet.sh client originate contract likaicontract for likaitest transferring 10 from likaitest running test.fi.ml --init '{},2,{"tz1UwLrUSCznFfdsiRmmw1dYZLXMnVsnq38z";"tz1cVmYsgYSux2Ng7cgH9FpybMNdUKAdtChy";"tz1eSeLtoZwbi6hCbepRcsoQiLzTaeAMK59J"}'

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/38914615/53852299-8f4ce300-3ffc-11e9-9930-4c0bc09b946a.png">

**Comment by purplecity** [comment]
I get a information. If a KT1 has no code it will be of type UnitContract.instance. If it has code, it must take a unit as parameter for it to be used. but ... the true scene is： transfer tezos between 2 KT1 address which has Michelson code(because this 2 KT1 address are multisign address. need owners). so  it is possible direct transfer tezos between 2 KT1 address which has code?

<img width="791" alt="image" src="https://user-images.githubusercontent.com/38914615/53853292-cf619500-3fff-11e9-809f-6e91c7a65427.png">

**Comment by stephenandrews** [comment]
The initial storage would be : 

```
(Pair {} (Pair 2 {"tz1UwLrUSCznFfdsiRmmw1dYZLXMnVsnq38z";"tz1cVmYsgYSux2Ng7cgH9FpybMNdUKAdtChy";"tz1eSeLtoZwbi6hCbepRcsoQiLzTaeAMK59J"}))
```

That contract can only send to codless smart contracts (or smart contracts that have unit as the param), as well as tz addresses. To send to contract with a param is a lot harder

**Comment by purplecity** [comment]
<img width="916" alt="image" src="https://user-images.githubusercontent.com/38914615/53876089-02784880-4041-11e9-818a-035e41aa244e.png">


the fi is :  

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/38914615/53876166-29367f00-4041-11e9-81c0-cde6732ec5ca.png">


where I wrong？

**Comment by stephenandrews** [comment]
Looks like you are using docker? I don't know how to link to a file using that, may pay to research that as I don't think test.fi.ml is in the container.

You can just use the raw output though, so print the contents of the file within single quotes instead of referencing a file name.

Also, you're missing a closing bracket on the init - refer to my other message
